const flavors=['Hot Honey','BBQ','Buffalo','Garlic Parmesan','Hot Honey Lemon Pepper'];
const drinks=['Coke','Sprite','Dr Pepper','Kool-Aid','No Drink'];
const wingChoices=[{label:'Wing type',values:['Bone-In','Boneless']},{label:'Flavor',values:flavors},{label:'Fries',values:['Regular Fries','Loaded Fries (+$2.00)']},{label:'Drink',values:drinks.slice(0,3)}];
const wings=[{id:'wing5',name:'5 Piece Wing Meal',price:10,note:'Includes fries and a drink',choices:wingChoices},{id:'wing10',name:'10 Piece Wing Meal',price:15,note:'Includes fries and a drink',choices:wingChoices}];
const specials=[{id:'boudin',name:'Boudin Balls',price:5,note:'2 crispy boudin balls',badge:'Weekly favorite'}];
const sweets=[
 {id:'cake-s',name:'Small Mini Cake',price:2.5,choices:[{label:'Flavor',values:['Oreo','Biscoff','Red Velvet','Strawberry Crunch','Banana Pudding']}]},{id:'cake-l',name:'Large Mini Cake',price:4,choices:[{label:'Flavor',values:['Oreo','Biscoff','Red Velvet','Strawberry Crunch','Banana Pudding']}]},{id:'cookie',name:'Cookie',price:2,choices:[{label:'Flavor',values:['Oreo','Red Velvet','Strawberry Crunch','Sprinkles','Biscoff']}]},{id:'cupcake',name:'Cupcake',price:2,choices:[{label:'Flavor',values:['Strawberry Crunch','Oreo','Red Velvet','Chocolate','Biscoff','Sprinkles']}]},{id:'cup6',name:'6 Cupcakes',price:12,choices:[{label:'Flavor',values:['Strawberry Crunch','Oreo','Red Velvet','Chocolate','Biscoff','Sprinkles']}]},{id:'cup12',name:'12 Cupcakes',price:24,choices:[{label:'Flavor',values:['Strawberry Crunch','Oreo','Red Velvet','Chocolate','Biscoff','Sprinkles']}]},{id:'cup24',name:'24 Cupcakes',price:48,choices:[{label:'Flavor',values:['Strawberry Crunch','Oreo','Red Velvet','Chocolate','Biscoff','Sprinkles']}]},{id:'brownie',name:'Brownie',price:1.5},{id:'rice',name:'Rice Krispie Treat',price:2},{id:'pretzel',name:'Chocolate Covered Pretzel',price:1},{id:'oreo',name:'3 Oreo Balls',price:5},{id:'straw6',name:'6 Chocolate Covered Strawberries',price:12},{id:'straw12',name:'12 Chocolate Covered Strawberries',price:24},{id:'straw24',name:'24 Chocolate Covered Strawberries',price:48}];
let cart=[];try{cart=JSON.parse(localStorage.getItem('janasyaCart')||'[]')}catch(e){}
const money=n=>'$'+Number(n).toFixed(2), sms=body=>location.href='sms:9125929236?&body='+encodeURIComponent(body);
function card(item){const choices=(item.choices||[]).map(c=>`<label>${c.label}<select data-choice="${c.label}">${c.values.map(v=>`<option>${v}</option>`).join('')}</select></label>`).join('');return `<article class="menu-card" data-id="${item.id}">${item.badge?`<span class="badge">${item.badge}</span>`:''}<div class="card-top"><h3>${item.name}</h3><strong class="item-price">${money(item.price)}</strong></div>${item.note?`<p>${item.note}</p>`:''}${choices}<div class="item-quantity"><span>Quantity</span><div><button type="button" data-minus>−</button><b data-amount>1</b><button type="button" data-plus>+</button></div></div><button class="primary-btn" data-add>Add 1 to cart • ${money(item.price)}</button></article>`}
function renderMenus(){wingMenu.innerHTML=wings.map(card).join('');specialMenu.innerHTML=specials.map(card).join('')+'<article class="special-note"><span>NEW EACH WEEK</span><h3>More specials coming soon</h3><p>Follow our pages to see what\'s cooking next.</p></article>';soulMenu.innerHTML=card({id:'soul',name:'Soul Food Sunday Plate',price:15,choices:[{label:'Drink',values:drinks}]});sweetMenu.innerHTML=sweets.map(card).join('')}
function itemById(id){return [...wings,...specials,...sweets,{id:'soul',name:'Soul Food Sunday Plate',price:15}].find(i=>i.id===id)}
function cardInfo(el){const item=itemById(el.dataset.id),selections={};el.querySelectorAll('[data-choice]').forEach(s=>selections[s.dataset.choice]=s.value);const qty=+el.querySelector('[data-amount]').textContent;const price=item.price+(selections.Fries?.startsWith('Loaded Fries')?2:0);return{item,selections,qty,price}}
document.addEventListener('click',e=>{const el=e.target.closest('.menu-card');if(el&&(e.target.matches('[data-plus]')||e.target.matches('[data-minus]'))){const n=el.querySelector('[data-amount]');n.textContent=Math.max(1,+n.textContent+(e.target.matches('[data-plus]')?1:-1));updateCard(el)}if(el&&e.target.matches('[data-add]'))addCart(cardInfo(el));if(e.target.matches('[data-close]')||e.target===overlay)closeAll();if(e.target.closest('[data-cart-minus]'))changeQty(e.target.closest('[data-cart-minus]').dataset.cartMinus,-1);if(e.target.closest('[data-cart-plus]'))changeQty(e.target.closest('[data-cart-plus]').dataset.cartPlus,1)});
document.addEventListener('change',e=>{if(e.target.matches('[data-choice]'))updateCard(e.target.closest('.menu-card'))});
function updateCard(el){const x=cardInfo(el);el.querySelector('.item-price').textContent=money(x.price);el.querySelector('[data-add]').textContent=`Add ${x.qty} to cart • ${money(x.price*x.qty)}`}
function addCart(x){const key=x.item.id+JSON.stringify(x.selections),old=cart.find(i=>i.key===key);if(old)old.qty+=x.qty;else cart.push({id:x.item.id,name:x.item.name,price:x.price,selections:x.selections,qty:x.qty,key});save();showToast(`${x.qty} ${x.item.name} added`)}
function changeQty(key,n){const x=cart.find(i=>i.key===key);if(x)x.qty+=n;cart=cart.filter(i=>i.qty>0);save()}
function save(){localStorage.setItem('janasyaCart',JSON.stringify(cart));renderCart()}
function renderCart(){const count=cart.reduce((n,i)=>n+i.qty,0),total=cart.reduce((n,i)=>n+i.price*i.qty,0);cartCount.textContent=count;checkoutItems.textContent=count+' items';checkoutTotal.textContent=cartTotal.textContent=money(total);cartList.innerHTML=cart.length?cart.map(i=>`<div class="cart-row"><div><b>${i.name}</b><small>${Object.values(i.selections).join(' • ')}</small><span>${money(i.price*i.qty)}</span></div><div class="qty"><button data-cart-minus="${i.key}">−</button><b>${i.qty}</b><button data-cart-plus="${i.key}">+</button></div></div>`).join(''):'<div class="empty">🛍️<p>Your cart is ready for something delicious.</p></div>'}
function openThing(el){overlay.classList.remove('hidden');el.classList.remove('hidden');if(el===cartPanel)el.classList.add('open')}
function closeAll(){overlay.classList.add('hidden');[galleryModal,cateringModal].forEach(x=>x.classList.add('hidden'));cartPanel.classList.remove('open')}
cartButton.onclick=()=>openThing(cartPanel);galleryButton.onclick=()=>openThing(galleryModal);cateringButton.onclick=()=>openThing(cateringModal);continueCheckout.onclick=closeAll;
galleryGrid.innerHTML=Array.from({length:18},(_,i)=>`<img src="https://janasyas-kitchen.janasyarivers14.chatgpt.site/gallery/food-${String(i+1).padStart(2,'0')}.jpg" alt="Janasya's Kitchen food ${i+1}" loading="lazy">`).join('');
function showToast(s){toast.textContent=s;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}
checkoutForm.onsubmit=e=>{e.preventDefault();if(!cart.length)return showToast('Add an item first.');const f=new FormData(e.target),lines=cart.map(i=>`${i.qty} x ${i.name}${Object.values(i.selections).length?' ('+Object.values(i.selections).join(', ')+')':''} - ${money(i.price*i.qty)}`).join('\n'),total=cart.reduce((n,i)=>n+i.price*i.qty,0);sms(`NEW JANASYA'S KITCHEN ORDER\n\nName: ${f.get('name')}\nPhone: ${f.get('phone')}\nPickup: ${f.get('time')}\nPayment: ${f.get('payment')}\nNotes: ${f.get('notes')||'None'}\n\n${lines}\n\nTOTAL: ${money(total)}\n\nPlease confirm my pickup order.`)};
reviewForm.onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);sms(`NEW REVIEW\n\nName: ${f.get('name')}\nRating: ${f.get('rating')} stars\nReview: ${f.get('review')}`)};
cateringForm.onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);sms(`NEW CATERING REQUEST\n\nName: ${f.get('name')}\nPhone: ${f.get('phone')}\nEvent: ${f.get('event')}\nDate/time: ${f.get('date')}\nGuests: ${f.get('guests')}\nLocation: ${f.get('location')}\nDetails: ${f.get('details')||'None'}`)};
renderMenus();renderCart();
